package sfmainframe.ship;

public enum Parameter {
    IS_WRECK, IS_SUNK, IS_IMMOBILIZED, IS_EXPLOSIVE, ACTIONS_OVER, SAILES_RIPPED, TURN_ESCAPE_ATTEMPT_USED, PULL_ON_ANCHOR_ATTEMPT_CARRIED, TOWED_BY_ONE_ATTEMPT_CARRIED
}
